#+TITLE: Examen de física EVAU 2016-2017
#+DESCRIPTION: Resolución del examen
#+AUTHOR: Marcel Gisbert
#+STARTUP: showall entitiespretty
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper]
#+LANGUAGE: es
#+OPTIONS: date:nil \n:t toc:nil
#+OPTIONS: ^:{}
* Opción A
** Pregunta 1
*** Enunciado
Titania, satélite del planeta Urano, describe una órbita circular en torno al planeta. Las aceleraciones de la gravedad en la superficie de Urano y de Titania son g_{u} = 8,69ms^{-2} y g_{t} = 0,37ms^{-2}, respectivamente. Un haz de luz emitido desde la superficie de Urano tarda 1,366s en llegar a la superficie de Titania. Determine:
 a) El radio de la órbita de Titania alrededor de Urano (distancia entre los centros de ambos cuerpos).
 b) El tiempo que tarda Titania en dar una vuelta completa alrededor de Urano, expresado en días terrestres.

/Datos: Constante de Gravitación Universal, G = 6,67·10^{-11} Nm²kg^{-2}, Velocidad de la luz en el vacío, c = 3·10⁸ms^{-1}; Masa de Usano, M_{u} = 8,69·10^{25} kg; Masa de Titania M_{t} = 3,53·10^{21} kg./

*** Respuesta
a)
#+BEGIN_EXPORT latex
\begin{equation}
g_{u} = G\frac{M}{R^{2}} \rightarrow 8,69\tfrac{m}{s} = 6,67 \cdot 10^{-11} \tfrac{Nm^{2}}{kg^{2}} \cdot \frac{8,69\cdot10^{25}kg}{R^{2}}
\end{equation}
\begin{equation}
R_{u}=\sqrt{\frac{6,67 \cdot 10^{-11} \frac{ \left( \frac{kg \cdot m}{s^{2}} \right) m^{2}}{kg^{2}} \cdot 8,69\cdot10^{25}kg}{8,69 \frac{m}{s^{2}}}} = \mathbf{2,58 \cdot 10^{7}m}
\end{equation}
\begin{equation}
g_{t} = G\frac{M}{R^{2}} \rightarrow 0,37\tfrac{m}{s} = 6,67 \cdot 10^{-11} \tfrac{Nm^{2}}{kg^{2}} \cdot \frac{3,53\cdot10^{21}kg}{R^{2}}
\end{equation}
\begin{equation}
R_{t}=\sqrt{\frac{6,67 \cdot 10^{-11} \frac{ \left( \frac{kg \cdot m}{s^{2}} \right) m^{2}}{kg^{2}} \cdot 3,53\cdot10^{21}kg}{0,37 \frac{m}{s^{2}}}} = \mathbf{7,98 \cdot 10^{5}m}
\end{equation}
\begin{equation}
c=\frac{h}{t} \rightarrow 3 \cdot 10^{8}\tfrac{m}{s} = \frac{h}{1,366s} \rightarrow h = 3 \cdot 10^{8} \tfrac{m}{s} \cdot 1,366s = 4,098 \cdot 10^{8}m
\end{equation}
\begin{equation}
R_{o} = R_{u} + R_{t} + h = 2,58 \cdot 10^{7}m + 7,98 \cdot 10^{5}m + 4,098 \cdot 10^{8}m = \mathbf{4,36 \cdot 10^{8}m}
\end{equation}
#+END_EXPORT

b)
#+BEGIN_EXPORT latex
\begin{equation}
v = \frac{s}{t} \rightarrow \omega = \frac{2 \pi r}{t} 
\end{equation}
\begin{equation}
F_{c} = F_{G} \rightarrow \frac{mv^{2}}{r} = G \frac{Mm}{r^{2}} \rightarrow v^{2} = \frac{GM}{r} 
\end{equation}
\begin{equation}
\left(\frac{2 \pi r}{t}\right)^{2} = \frac{GM}{r} \rightarrow 4 \pi ^{2} r^{3} = t^{2} G M \rightarrow t = \sqrt{\frac{4 \pi ^{2} r^{3}}{GM}} 
\end{equation}
\begin{equation}
t=\sqrt{\frac{4 \cdot 3,14^{2} \cdot \left(4,436 \cdot 10^{8}\right)^{3}}{6,67 \cdot 10^{11} \cdot 8,69 \cdot 10^{25}}} = \sqrt{5,939 \cdot 10^{11} s} =770.680,099 s 
\end{equation}
\begin{equation}
\frac{770.680,099 s}{60 \cdot 60 \cdot 24 \tfrac{s}{dia}} = \mathbf{8,92 dias}
\end{equation}
#+END_EXPORT

* Opción B
** Pregunta 1
*** Enunciado
Un cierto planeta esférico tiene de masa, el doble de la masa de la Tierra y la longitud de su circunferencia ecuatorial mide la mitad de la de la Tierra. Calcule:
a) La relación que existe entre la velocidad de escape en la superficie de dicho planeta con respecto a la velocidad de escape en la superficie de la Tierra.
b) La aceleración de la gravedad en la superficie del planeta.
/Dato: Aceleración de la gravedad en la superficie de la Tierra, g_{t} = 9,81 m s^{-2}./

*** Respuesta
a)
#+BEGIN_EXPORT latex
\begin{equation}
F_{c} = F_{G} \rightarrow \frac{mv^{2}}{r} = G \frac{Mm}{r^{2}} \rightarrow v_{T} = \sqrt{\frac{GM_{T}}{r_{T}}}
\end{equation}
\begin{equation}
v_{P} = \sqrt{\frac{G2M_{T}}{\frac{1}{2}r_{T}}}
\end{equation}
#+END_EXPORT

b)
#+BEGIN_EXPORT latex
\begin{equation}
g_{T} = G\frac{M_{T}}{R_{T}^{2}} \rightarrow g_{P} = G\frac{2M_{T}}{\frac{1}{2}R_{T}}
\end{equation}
\begin{equation}
\frac{g_{T}}{g_{P}} = \frac{G\frac{M_{T}}{R_{T}^{2}}}{G\frac{2M_{T}}{\frac{1}{2}R_{T}}}
\end{equation}
\begin{equation}
\frac{g_{T}}{g_{P}} = \frac{1}{4} \rightarrow g_{P} = 4 \cdot g_{T} = 4 \cdot 9,81 = \mathbf{39.24 m s^{-2}}
\end{equation}
#+END_EXPORT
