#+TITLE: Curso de química de 2º de Bachillerato
#+DESCRIPTION: Aprendizaje, ejemplos y ejercicios del libro de Anaya
#+AUTHOR: Marcel Gisbert
#+STARTUP: showall entitiespretty
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper]
#+LANGUAGE: es
#+OPTIONS: date:nil \n:t toc:t
* Naturaleza de la materia
** Clasificación de la materia
** Las leyes ponderales
*** Ejercicios resueltos
1 Al reaccionar 1,50g de hierro con 1,50g de azufre, queda un exceso de 0,64g de azufre. Si ahora hacemos reaccionar 1,80g de hierro con 0,80g de azufre:
 a) ¿Quedará alguna sustancia en exceso?
#+BEGIN_EXPORT latex
\begin{equation}
1,50g - 0,64g = 0,86g \text{reaccionan con 1,50g de Fe}
\end{equation}
\begin{equation}
R_1 = \frac{1,50}{0,86} = 1,74 \Rightarrow 1,74 : 1
\end{equation}
\begin{equation}
R_2 = \frac{1,80}{0,80} = 2,25 \Rightarrow 2,25 > 1,74 \Rightarrow \text{exceso de Fe}
\end{equation}
\begin{equation}
0,80 \cdot 1,74 = 1,39 \Rightarrow 1,80 - 1,39 = 0,41g \quad Fe
\end{equation}
#+END_EXPORT
 b) ¿Qué masa de sulfuro de hierro se formará?
#+BEGIN_EXPORT latex
\begin{equation}
0,80g \quad S \quad + 1,39g \quad Fe \quad = 2,19g \quad FeS
\end{equation}
#+END_EXPORT
 c) ¿Cuál es el porcentaje en masa de cada elemento químico en el compuesto?
#+BEGIN_EXPORT latex
\begin{equation}
\frac{FeS 2,19}{Fe 1,39} = \frac{100\%}{x} \Rightarrow x = 63,47\%
\end{equation}
\begin{equation}
\frac{FeS 2,19}{S 0,80} = \frac{100\%}{y} \Rightarrow y = 36,53\%
\end{equation}
#+END_EXPORT

2 El oxígeno y el plomo forman dos óxidos diferentes.
  El primero de ellos tiene un 7,2% de oxígeno, y el segundo, 13,4%.
  Comprueba que se cumple la ley de las proporciones múltiples.
#+BEGIN_EXPORT latex
\begin{equation}
\text{Primer óxido} \quad 7,2 \quad \Rightarrow \quad
\begin{matrix}
1g \rightarrow 100\% \\
x  \rightarrow 7,2\%
\end{matrix}
\quad \rightarrow \quad \text{0,072g Oxígeno}
\end{equation}
\begin{equation}
1g PbO - 0,072 O = 0,928 Pb
\qquad R \Rightarrow \quad \frac{0,928}{0,072} \quad \Rightarrow \quad 12,89 : 1
\end{equation}
\begin{equation}
\text{Segundo óxido} \quad 13,4 \quad \Rightarrow \quad
\begin{matrix}
1g \rightarrow 100\% \\
x \rightarrow 13,4\%
\end{matrix}
\quad \rightarrow \quad \text{0,134g Oxígeno}
\end{equation}
\begin{equation}
1g PbO - 0,134 O = 0,866 Pb
\qquad R \Rightarrow \quad \frac{0,866}{0,134} \quad \Rightarrow \quad 6,46 : 1
\end{equation}
\begin{equation}
PM \Rightarrow \frac{12,89}{6,46} = \frac{1}{2} \quad \textbf{Sí cumple}
\end{equation}
#+END_EXPORT
*** Actividades
2. El oxígeno se combina con el silicio en una relación de masa 1,14:1
 a) ¿Qué masa de silicio es necesaria para reaccionar con 1g de oxígeno?
#+BEGIN_EXPORT latex
\begin{equation}
\begin{matrix}
1,14g & \rightarrow & 1g \\
1g    & \rightarrow & x
\end{matrix}
\quad \Rightarrow \quad \text{0,88g Si}
\end{equation}
#+END_EXPORT

 b) ¿Qué masa de óxido de silicio se formará?
#+BEGIN_EXPORT latex
\begin{equation}
O \quad 1g + Si \quad 0,88 = 1,88 \quad SiO_2
\end{equation}
#+END_EXPORT

3. De acuerdo con los datos del ejercicio resuelto 1, explica qué ocurrirá si hacemos reaccionar:
 a) 3,0g de Fe con 5,0g de S.
#+BEGIN_EXPORT latex
\begin{equation}
\frac{3,0g \quad Fe}{1,74g \quad S} = 1,72 \quad FeS
\end{equation}
\text{3g de Fe reaccionan con 1,72g de S y sobran 3,28g de S} \\
\text{Se forman 3 + 1,72 = 4,72g de FeS}
#+END_EXPORT

 b) 4,0mg de Fe con 2,0mg de S.
2 x 1,74 = 3,14mg Fe reaccionan con 2mg S
Se forman 5,48mg FeO y sobran 4,0 - 3,48 = 0,52mg Fe

 c) 6,09kg de Fe con 3,5kg de S.
Reacciona exactamente todo y forma 9,59kg FeS

** Teoría atómica de Dalton
*** Ejercicios resueltos
3. Tenemos dos muestras de óxido de cromo, la primera de 12,4g, y la segunda, de 16,9g. Su análisis químico nos indica que en la primera hay 9,5g del metal, y 11,7g en la segunda. ¿Se trata del mismo compuesto?
12,4 g -  9,5 g = 2,9 g de oxígeno
16,9 g - 11,7 g = 5,2 g de oxígeno
Proporción 1º: 2,9/9,5x100 = 30,5%
Proporción 2º: 5,2/11,7x100 = 44,4%
No son el mismo compuesto.
*** Actividades
4. Justifica, a partir de la teoría de Dalton, por qué la composición porcentual de un compuesto es fija y constante.
5. ¿Por qué
6. Cada una de las siguientes proposiciones cuestiona alguna de las hipótesis de Dalton. Indícalas.
 a) El oxígeno tiene varios isótopos. 2ª
 b) Lo electrones y los protones son partículas subatómicas. 1ª
 c) La fórmula molecular de la sacarosa (azúcar) es C_12 H_22 O_11 . 3ª

** Ley de Avogadro
*** Actividades
7. Experimentalmente se...
1 litro de hidrógeno + 1 litro de cloro = 2 litros de HCl -> HCl
8. Tenemos dos recipientes...
a) ¿Dónde hay mayor número de moléculas? ¿Por qué?
Como ocupan el mismo volumen, contienen el mismo número de moléculas
b) ¿Qué relación existe entre las masas de una molécula de acetileno y una de cloro?
0,391 / 0,143 = 2,7:1
9. ¿Por qué unas veces se habla de hipótesis de Avogadro y otras de ley de Avogadro?
Porque se produce antes o después de la confirmación experimental.
*** Ejercicios resueltos
4. Calcula el volumen de vapor de agua que podemos obtener a partir de 80 L de oxígeno. Expresa el resultado en metros cúbicos.
Agua = H_2 O => Relación de oxígeno en el agua => 1:2
#+BEGIN_EXPORT latex
\begin{equation}
\frac{1 L oxígeno}{2 L agua}=\frac{80 L oxígeno}{volumen} \Rightarrow volumen = 160 L
\end{equation}
\begin{equation}
volumen = 160 L \quad \frac{10^{-3} m^3}{1 L} = 0,16 m^3
\end{equation}
#+END_EXPORT
5. Tenemos dos recipientes en las mismas condiciones de presión y temperatura. El primer contiene 0,95g de butano, y el segundo, de doble volumen, 1,05g de oxígeno.
a) Compara el número de moléculas que hay en los dos recipientes
A doble volumen, doble cantidad de moléculas de oxígenos que de butano.
b) ¿Qué relación hay entre la masa de una molécula de butano y una de oxígeno?
1,05g de oxígeno en doble volumen significa que 1,05/2 = 0,525g de oxígeno en el mismo volumen
0,525g oxígeno / 0,95g butano = 0,553 => 1,81:1
6. Sabemos que 1 L de nitrógeno reacciona con 3 L de hidrógeno para dar 2 L de amoniaco. Determina la fórmula molecular del amoniaco. ¿Se conserva el número de moléculas?
1·n moléculas N_2 + 3·n moléculas H_2 = 2·n moléculas amoniaco
Por cada molécula hay:
2·N y 2·H
Por tanto:
1·2·N + 3·2·H = 2·amoniaco
2N + 6H = 2 amoniaco => 1N+3H = NH_3
7.
